### ISSUE TITLE
problem with `method = "AV"`

### ISSUE THREAD

**Issue by magnusdv** [thoree/mut2#1]
When I try to knit the vignette I'm getting the following error:

``` r
library(pedmut)
library(mut2)

Q = mutationMatrix("equal", rate = 0.003, alleles = 1:4)
p = c(0.1,0.3,0.4,0.2)
names(p) = 1:4

P2 = findReversible(Q, afreq = p, method = "AV")
#> Error in findReversible(Q, afreq = p, method = "AV"): Methods needs to be 'MH', 'PM' or 'BA'
```

<sup>Created on 2023-03-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by thoree** [comment]
This should now be fixed and pushed: The reversing method 'AV' is renamed to 'PM'. I also added a SNP example at the end of the vignette
